apiVersion: v1
kind: Service
metadata:
  name: sia-eventui-ppe-service
  labels:
    run: sia-eventui-ppe
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: http
  selector:
    run: sia-eventui-ppe
    
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sia-eventui-ppe 
spec:
  selector:
    matchLabels:
      run: sia-eventui-ppe
  replicas: 1
  template:
    metadata:
      labels:
        run: sia-eventui-ppe
    spec:
      containers:
          - name: sia-eventui-dist
            image: siacontainerregistry.azurecr.io/azure/sia-eventui-dist:0
            env:
              - name: NODE_ENV
                value: dist
            ports:
              - containerPort: 3000

